### ISSUE TITLE
Broken Pages

### ISSUE THREAD

**Issue by xSESILx** [romancmx/gamebrary#51]
When you updated to gamebrary from switchlist, all of my listed switch games are gone and I see no way to locate or add them again. Please assist.

![switch games missing](https://user-images.githubusercontent.com/41349584/49537728-eec51680-f886-11e8-80b0-d97b27021ccd.JPG)

**Comment by romancm** [comment]
please send me the email address you used before to contact@gamebrary.com and I can migrate your old data.

**Comment by romancm** [comment]
Also, you may have a cached version of the app, please do a hard reload  to get the latest version to show.

**Comment by romancmx** [comment]
Data migrated, you should probably logout and log back in to see your synced data.
