### ISSUE TITLE
Can't remove platform

### ISSUE THREAD

**Issue by GMartigny** [romancmx/gamebrary#52]
Hi,

Once you clicked on a platform, it's added to your list. Then, it's not possible to remove it. Even if you empty it.

The app could either have a button or remove them automatically when there's no list inside.

**Comment by romancmx** [comment]
That's a great idea! PR merged https://github.com/romancmx/gamebrary/pull/53. Deployed in release [v1.3.0](https://github.com/romancmx/gamebrary/releases/tag/v1.3.0)

**Comment by romancm** [comment]
@all-contributors please add @GMartigny for bug
