### ISSUE TITLE
Drag-and-Drop is broken

### ISSUE THREAD

**Issue by areyouokani** [romancmx/gamebrary#55]
Drag-and-drop doesn't work as of February 16. Tested on the desktop and mobile Chrome. The "hand" button is clickable, but dragging doesn't produce anything and it's impossible to move a card to another list.

**Comment by romancmx** [comment]
Oops, I accidentally removed the css class. [Fixed now](https://github.com/romancmx/gamebrary/releases/tag/v1.10.5). Thanks for reporting it!
